name: Workflow setup
description: Shared action to setup workflows
inputs:
  node:
    description: "node version"
    required: true
  npmToken:
    description: "NPM token"
    required: true
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node }}
    - name: Get yarn v3 cache directory
      id: get-yarn3-cache
      run: |
        echo "::group::Get yarn cache directory"
        echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
        echo "::endgroup::"
      shell: bash
    - name: Restore yarn cache directory
      id: restore-yarn-cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.get-yarn3-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - run: |
        yarn config set npmAuthToken ${{ inputs.npmToken }} --home
        yarn install --immutable
      shell: bash