name: Workflow setup
description: Shared action to setup workflows
inputs:
  node:
    description: "node version"
    required: true
  npmToken:
    description: "NPM token"
    required: true
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node }}
    - id: cache
      run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      shell: bash
    - uses: actions/cache@v3
      with:
        path: ${{ steps.cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - run: |
        echo "//registry.npmjs.org/:_authToken=${{ inputs.npmToken }}" >> ~/.npmrc
        yarn install --frozen-lockfile
      shell: bash