name: ci-cd
on:
  push:
    branches:
      - '**/*'
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  unit:
    name: Unit
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        node: [18, 19, 20]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || '' }}
      - uses: ./.github/actions/setup
        with:
          node: ${{ matrix.node }}
          npmToken: ${{ secrets.NODE_AUTH_TOKEN }}
      - run: yarn build:license-checker
      - run: yarn flow start
      - run: yarn test
      - uses: actions/upload-artifact@v3
        with:
          name: upload-artifacts
          path: var
