name: Package Checker
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
permissions:
  contents: read
  pull-requests: write
jobs:
  package-checker:
    name: Package Checker
    uses: CumulusDS/workflows-public/.github/workflows/packages.yml@master
    secrets: inherit
