name: Package Checker
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
permissions:
  contents: read
  pull-requests: write
jobs:
  yarn:
    name: Yarn Lock Changes
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: Simek/yarn-lock-changes@v0.11.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
