name: Publish
on:
  release:
    types: [released]
jobs:
  unit:
    name: Unit
    if: github.event_name == 'release'
    uses: CumulusDS/workflows-public/.github/workflows/package-publish.yml@master
    secrets: inherit
    with:
      access: public
